---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: us-east-2
  version: "1.22"

availabilityZones: ["us-east-2a", "us-east-2b", "us-east-2c"]

vpc:
  cidr: "10.10.0.0/16"

managedNodeGroups:
- amiFamily: AmazonLinux2
  instanceType: m5.xlarge
  name: mng-od-m5large
  desiredCapacity: 2
  maxSize: 10
  minSize: 0
  iam:
    withAddonPolicies:
      autoScaler: true
      cloudWatch: true
      albIngress: true
  privateNetworking: true
  
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

fargateProfiles:
  - name: kube-system-profile
    selectors:
      - namespace: kube-system
# To enable all of the control plane logs, uncomment below:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]