apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: podinfo-fp
  labels:
    app: podinfo
spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http